version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: grammar_db
      POSTGRES_USER: grammar_user
      POSTGRES_PASSWORD: grammar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zayasgrammar.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: